import Image from "next/image";
import { Inter } from "next/font/google";
import Projects3 from "@/components/Projects3";
import Head from "next/head";
import Footer from "@/components/Footer";
import Contact from "@/components/Contact";
import Header from "@/components/Header";
import About from "@/components/About";
import TechStack from "@/components/TechStack";
import Banner from "@/components/Banner";
import AboutMe2 from "@/components/AboutMe2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Md Shakil Chowdhury</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden">
        <Header />
        <Banner />
        {/* <About /> */}
        <AboutMe2 />
        <TechStack />
        <Projects3 />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
